#!/usr/bin/env python
# encoding: utf-8


def build(ctx):
    ctx.stlib(
        target="antlisp-lib-parser",
        source = [
            "parser.cpp",
        ],
        use=[
            "antlisp-lib-util",
            "antlisp-lib-function",
            "antlisp-lib-function-builtin",
            # in
            "antlisp-lib-parser-cell",
            "antlisp-lib-parser-parentheses",
        ],
    )

    ctx.program(
        target="parser_ut",
        features="test",
        source="parser_ut.cpp",
        use=[
            "antlisp-lib-parser",
            "antlisp-lib-function-builtin",
        ],
        lib=[
            "boost_filesystem",
            "boost_system",
        ],
    )
    ctx.program(
        target="parse_and_run_ut",
        features="test",
        source="parse_and_run_ut.cpp",
        use=[
            "antlisp-lib-parser",
            "antlisp-lib-function-builtin",
        ],
        lib=[
            "boost_filesystem",
            "boost_system",
        ],
    )
    ctx.recurse([
        "cell",
        "parentheses",
    ])
