#!/usr/bin/env python
# encoding: utf-8


def build(ctx):
    ctx.stlib(
        target="antlisp-lib-parser",
        source = [
            "code_stream.cpp",
            "parser.cpp",
            "parentheses_parser.cpp",
        ],
        use=[
            "antlisp-lib-function",
        ],
    )

    ctx.program(
        target="code_stream_ut",
        source="code_stream_ut.cpp",
        use=[
            "antlisp-lib-parser",
        ],
    )
    ctx(
        rule="${SRC}",
        source="code_stream_ut",
    )

    ctx.program(
        target="parentheses_parser_ut",
        source="parentheses_parser_ut.cpp",
        use=[
            "antlisp-lib-parser",
        ],
    )
    ctx(
        rule="${SRC}",
        source="parentheses_parser_ut",
    )

    ctx.program(
        target="parser_ut",
        source="parser_ut.cpp",
        use=[
            "antlisp-lib-parser",
        ],
    )
    ctx(
        rule="${SRC}",
        source="parser_ut",
    )

    ctx.program(
        target="parse_and_run_ut",
        source="parse_and_run_ut.cpp",
        use=[
            "antlisp-lib-parser",
        ],
    )
    ctx(
        rule="${SRC}",
        source="parse_and_run_ut",
    )
