#!/usr/bin/env python
# encoding: utf-8


def build(ctx):
    ctx.stlib(
        target="antlisp-lib-util",
        source = [
            "string.cpp",
        ],
        use=[
        ],
    )

    ctx.program(
        target="exception_ut",
        features="test",
        source="exception_ut.cpp",
        use=[
        ],
    )
    ctx.program(
        target="string_ut",
        features="test",
        source="string_ut.cpp",
        use=[
            "antlisp-lib-util"
        ],
    )
