#!/usr/bin/env python
# encoding: utf-8


def build(ctx):
    ctx.stlib(
        target="antlisp-lib-cell-array",
        source = [
            "array.cpp",
        ],
        use=[
            "antlisp-lib-cell-ext",
            "antlisp-lib-name",
            "antlisp-lib-util",
        ],
    )

    ctx.program(
        target="array_ut",
        features="test",
        source="array_ut.cpp",
        use=[
            "antlisp-lib-cell-array",
        ],
    )
