#!/usr/bin/env python
# encoding: utf-8


def build(ctx):
    ctx.stlib(
        target="antlisp-lib-cell_ext-lisp_error",
        source = [
            "error.cpp",
        ],
        use=[
            "antlisp-lib-cell",
            "antlisp-lib-util",
        ],
    )

    ctx.program(
        target="lisp_error_ut",
        features="test",
        source="error_ut.cpp",
        use=[
            "antlisp-lib-cell_ext-lisp_error",
        ],
    )
