#!/usr/bin/env python
# encoding: utf-8


def build(ctx):
    ctx.stlib(
        target="antlisp-lib-cell",
        source = [
            "cell.cpp",
            "cell_type.cpp",
        ],
        use=[
            "antlisp-lib-util",
        ],
    )

    ctx.program(
        target="cell_ut",
        features="test",
        source="cell_ut.cpp",
        use=[
            "antlisp-lib-cell"
        ],
    )
