#!/usr/bin/env python
# encoding: utf-8


def build(ctx):
    ctx.stlib(
        target="antlisp-lib-load",
        source = [
            "load.cpp",
        ],
        use=[
            "antlisp-lib-util",
            "antlisp-lib-cell",
        ],
        lib=[
            "boost_filesystem",
            "boost_system",
        ],
    )
    ctx.program(
        target="load_ut",
        features="test",
        source="load_ut.cpp",
        use=[
            "antlisp-lib-load",
        ],
        lib=[
            "boost_filesystem",
            "boost_system",
        ],
    )
    ctx.recurse([
    ])
