#!/usr/bin/env python
# encoding: utf-8


def build(ctx):
    ctx.stlib(
        target="antlisp-lib-load",
        source = [
            "load.cpp",
        ],
        use=[
            "antlisp-lib-util",
            "antlisp-lib-function",
            "antlisp-lib-function-builtin",
            "antlisp-lib-parser-cell",
        ],
    )
    ctx.program(
        target="load_ut",
        features="test",
        source="load_ut.cpp",
        use=[
            "antlisp-lib-load",
        ],
    )
    ctx.recurse([
    ])
