#!/usr/bin/env python
# encoding: utf-8


def build(ctx):
    ctx.stlib(
        target="antlisp-src-parser",
        source = [
            "code_stream.cpp",
            #"parser.cpp",
        ],
        use=[
            "antlisp-src-function",
        ],
    )

    ctx.program(
        target="code_stream_ut",
        source="code_stream_ut.cpp",
        use=[
            "antlisp-src-parser",
        ],
    )
    ctx(
        rule="${SRC}",
        source="code_stream_ut",
    )

    #ctx.program(
    #    target="parser_ut",
    #    source="parser_ut.cpp",
    #    use=[
    #        "antlisp-src-parser",
    #    ],
    #)
    #ctx(
    #    rule="${SRC}",
    #    source="parser_ut",
    #)
    #
    #ctx.program(
    #    target="parse_and_run_ut",
    #    source="parse_and_run_ut.cpp",
    #    use=[
    #        "antlisp-src-parser",
    #    ],
    #)
    #ctx(
    #    rule="${SRC}",
    #    source="parse_and_run_ut",
    #)
