#!/usr/bin/env python
# encoding: utf-8


def build(ctx):
    ctx.stlib(
        target="antlisp-lib-cell-ext",
        source = [
            "mock.cpp",
        ],
        use=[
            "antlisp-lib-util",
            "antlisp-lib-cell-ext-string",
        ],
    )

    ctx.program(
        target="mock_ut",
        features="test",
        source="mock_ut.cpp",
        use=[
            "antlisp-lib-cell-ext"
        ],
    )

    ctx.recurse([
        "string",
    ])
