#!/usr/bin/env python
# encoding: utf-8


def build(ctx):
    ctx.stlib(
        target="antlisp-lib-name",
        source = [
            "name.cpp",
        ],
        use=[
            "antlisp-lib-util",
        ],
    )
