#!/usr/bin/env python
# encoding: utf-8


def build(ctx):
    ctx.stlib(
        target="antlisp-lib-exttypes",
        source = [
            "string.cpp",
        ],
        use=[
            "antlisp-lib-cell",
            "antlisp-lib-util",
        ],
    )

    ctx.program(
        target="string_ut",
        features="test",
        source="string_ut.cpp",
        use=[
            "antlisp-lib-ext-types",
        ],
    )
