#!/usr/bin/env python
# encoding: utf-8


def build(ctx):
    ctx.stlib(
        target="antlisp-lib-parser-parentheses",
        source = [
            "parentheses_parser.cpp",
        ],
        use=[
            "antlisp-lib-util",
            "antlisp-lib-parser-parentheses-code_stream",
        ],
    )

    ctx.program(
        target="parentheses_parser_ut",
        features="test",
        source="parentheses_parser_ut.cpp",
        use=[
            "antlisp-lib-parser-parentheses",
        ],
    )
    ctx.recurse([
        "code_stream",
    ])
