#!/usr/bin/env python
# encoding: utf-8


def build(ctx):
    ctx.stlib(
        target="antlisp-lib-function",
        source = [
            "tape_machine.cpp",
            "interface.cpp",
            "native_tape.cpp",
        ],
        use=[
            "antlisp-lib-cell",
        ],
    )
    ctx.program(
        target="tape_machine_ut",
        features="test",
        source="tape_machine_ut.cpp",
        use=[
            "antlisp-lib-function"
        ],
    )
    ctx.program(
        target="native_tape_ut",
        features="test",
        source="native_tape_ut.cpp",
        use=[
            "antlisp-lib-function"
        ],
    )
    ctx.recurse([
        "builtin",
    ])
