#!/usr/bin/env python
# encoding: utf-8


def build(ctx):
    ctx.stlib(
        target="antlisp-lib-function",
        source = [
            "stack_machine.cpp",
            "interface.cpp",
        ],
        use=[
            "antlisp-lib-cell",
        ],
    )
    ctx.program(
        target="stack_machine_ut",
        source="stack_machine_ut.cpp",
        use=[
            "antlisp-lib-function"
        ],
    )
    ctx(
        rule="${SRC}",
        source="stack_machine_ut",
    )
