#!/usr/bin/env python
# encoding: utf-8


def build(ctx):
    ctx.stlib(
        target="antlisp-src-util",
        source = [
            "string.cpp",
        ],
        use=[
        ],
    )

    ctx.program(
        target="exception_ut",
        source="exception_ut.cpp",
        use=[
        ],
    )
    ctx(
        rule="${SRC}",
        source="exception_ut",
    )

    ctx.program(
        target="string_ut",
        source="string_ut.cpp",
        use=[
            "antlisp-src-util"
        ],
    )
    ctx(
        rule="${SRC}",
        source="string_ut",
    )
