cc_library(
    name = "antlib",
    srcs = [
        "interface.cpp",
    ],
    hdrs = [
        "interface.h",
    ],
    deps = [
        "//antlisp/lib/builtin:builtin",
        "//antlisp/lib/cell:cell",
        "//antlisp/lib/cell_ext:ext",
        "//antlisp/lib/function:function",
        "//antlisp/lib/load:load",
        "//antlisp/lib/parser:parser",
        "//antlisp/lib/util:util",
    ],
    visibility = ["PUBLIC"],
)
