#!/usr/bin/env python
# encoding: utf-8


def build(ctx):
    ctx.stlib(
        target="antlisp-lib",
        source = [
            "interface.cpp",
        ],
        use=[
            "antlisp-lib-cell",
            "antlisp-lib-function",
            "antlisp-lib-parser",
            "antlisp-lib-util",
            "antlisp-lib-function-builtin",
            "antlisp-lib-cell_ext-string",
        ],
    )
    ctx.recurse([
        "cell",
        "cell_ext",
        "function",
        "load",
        "parser",
        "test",
        "util",
    ])
