#!/usr/bin/env python
# encoding: utf-8


def build(ctx):
    ctx.stlib(
        target="antlisp-lib-varname",
        source = [
            "prefix.cpp",
            "namespace.cpp",
        ],
        use=[
            "antlisp-lib-cell",
            "antlisp-lib-util",
        ],
    )
    ctx.program(
        target="prefix_ut",
        features="test",
        source="prefix_ut.cpp",
        use=[
            "antlisp-lib-varname"
        ],
    )
    ctx.program(
        target="namespace_ut",
        features="test",
        source="namespace_ut.cpp",
        use=[
            "antlisp-lib-varname"
        ],
    )
