#!/usr/bin/env python
# encoding: utf-8


def build(ctx):
    ctx.stlib(
        target="antlisp-src-cell",
        source = [
            "cell.cpp",
        ],
        use=[
            "antlisp-src-util",
        ],
    )

    ctx.program(
        target="cell_ut",
        source="cell_ut.cpp",
        use=[
            "antlisp-src-cell"
        ],
    )
    ctx(
        rule="${SRC}",
        source="cell_ut",
    )
