#!/usr/bin/env python
# encoding: utf-8


def build(ctx):
    ctx.stlib(
        target="antlisp-src",
        source = [
            "stack_machine.cpp",
            "cell.cpp",
            "string.cpp",
        ],
        use=[
        ],
    )
    ctx.program(
        target="stack_machine_ut",
        source="stack_machine_ut.cpp",
        use=[
            "antlisp-src"
        ],
    )
    ctx(
        rule="${SRC}",
        source="stack_machine_ut",
    )

    ctx.program(
        target="exception_ut",
        source="exception_ut.cpp",
        use=[
            "antlisp-src"
        ],
    )
    ctx(
        rule="${SRC}",
        source="exception_ut",
    )

    ctx.program(
        target="cell_ut",
        source="cell_ut.cpp",
        use=[
            "antlisp-src"
        ],
    )
    ctx(
        rule="${SRC}",
        source="cell_ut",
    )

    ctx.program(
        target="string_ut",
        source="string_ut.cpp",
        use=[
            "antlisp-src"
        ],
    )
    ctx(
        rule="${SRC}",
        source="string_ut",
    )
