#!/usr/bin/env python
# encoding: utf-8


def build(ctx):
    ctx.stlib(
        target="src-antlisp",
        source = [
            "stack_machine.cpp",
        ],
        use=[
        ],
    )
    ctx.program(
        target="stack_machine_ut",
        source="stack_machine_ut.cpp",
        use="arc-antlisp",
    )
    ctx(
        rule="${SRC}",
        source="stack_machine_ut",
    )
