#!/usr/bin/env python
# encoding: utf-8


def build(ctx):
    ctx.recurse([
        "lib",
        "bin",
    ])
    # tests result
    from waflib.Tools import waf_unit_test
    ctx.add_post_fun(waf_unit_test.summary)
    ctx.add_post_fun(waf_unit_test.set_exit_code)
